In [ ]:
import numpy as np
# this is a 2 by 7 array
a = np.array([[1,2,3,4,5,6,7,], [8,9,10,11,12,13,14]])
print(a)

a.shape

In [24]:
#get  specific value [r,c]
a[1,5]

13

In [29]:
# get a specific row
a[1, :] 

array([ 8,  9, 10, 11, 12, 13, 14])

In [32]:
# get specific column
a[:, 2]

array([ 3, 10])

In [39]:
#getting fancy startindex:endindex:stepsize
a[0, 1:6:2 ]



array([ 8, 10, 12, 14])

In [44]:
#changed 13 into 25
a[1,5] = 25

print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 25 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 25 14]]


In [50]:
#3d example

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [68]:
#get specific element (work outside in)

c[0,1,0]

3